## Setup

In [1]:
%load_ext autoreload
%autoreload 2

import plotly.io as pio
pio.renderers.default = "sphinx_gallery"
import plotly.express as px
import pandas as pd
import numpy as np
import datetime as dt
import itertools
import statsmodels.api as sm
import statsmodels.formula.api as smf
from leap.utils import date_range, TimeDelta
from leap.data_generation.utils import heaviside
from leap.data_generation.antibiotic_data import load_birth_data, convert_sex_to_numeric, \
    convert_timepoint_to_numeric

In [2]:
# Plot Settings
pio.templates.default = "plotly_white"
config = {
    'toImageButtonOptions': {
        'format': 'png',
        'scale': 2
    }
}

## Data

Since the antibiotic dosing data is private, we will create here a mock dataset. In this dataset,
we will have the *total* number of courses of antibiotics prescribed to all infants in BC,
stratified by sex and year.

In [3]:
# Data was collected for the years 2000-2018
years = list(date_range(start=dt.datetime(2000, 1, 1), stop=dt.datetime(2018, 12, 31), step=TimeDelta(years=1)))

# Mock data for antibiotic courses prescribed to infants using an approximate linear trend
n_abx_female = [-640 * i + 16000 for i, _ in enumerate(years)]
n_abx_male = [-880 * i + 22000 for i, _ in enumerate(years)]
n_abx = n_abx_female + n_abx_male

# Create a DataFrame for antibiotic courses prescribed to infants
df_abx = pd.DataFrame(
    data=list(itertools.product(["F", "M"], years)),
    columns=["sex", "timepoint"]
)
df_abx["n_abx"] = n_abx
df_abx.head()

  sex  timepoint  n_abx
0   F 2000-01-01  16000
1   F 2001-01-01  15360
2   F 2002-01-01  14720
3   F 2003-01-01  14080
4   F 2004-01-01  13440

Next, since the antibiotic data measures the number of antibiotics prescribed at a population level,
we need to use population data from `Statistics Canada` to determine the number of antibiotics
prescribed per capita:

In [4]:
df_birth = load_birth_data()
df_birth.head()

   timepoint province sex  n_birth
0 2000-01-01       BC   F    20118
1 2001-01-01       BC   F    19578
2 2002-01-01       BC   F    19279
3 2003-01-01       BC   F    19591
4 2004-01-01       BC   F    19529

We can now merge the `df_abx` and `df_birth` dataframes:

In [5]:
df = pd.merge(df_abx, df_birth, on=["timepoint", "sex"], how="left")
df.head()

  sex  timepoint  n_abx province  n_birth
0   F 2000-01-01  16000       BC    20118
1   F 2001-01-01  15360       BC    19578
2   F 2002-01-01  14720       BC    19279
3   F 2003-01-01  14080       BC    19591
4   F 2004-01-01  13440       BC    19529

In [6]:
color_map={
    "M": "#09bfc4",
    "F": "#f39c12",
}

fig = px.line(
    df,
    x="timepoint",
    y="n_abx",
    facet_col="sex",
    color="sex",
    labels={"n_abx": "Total Number of Antibiotic Courses Prescribed to Infant Population"},
    color_discrete_map=color_map
)
fig.update_xaxes(title_text="Birth Year", nticks=10)
fig.update_yaxes(title_font=dict(size=12))

fig.show()

## Model

In [7]:
df["sex"] = df["sex"].apply(convert_sex_to_numeric)
df["timepoint"] = df["timepoint"].apply(convert_timepoint_to_numeric)

In [8]:
formula = "n_abx ~ timepoint + sex + heaviside(timepoint, 2005.0) * timepoint"

Since we are using a simulated dataset, we set $\theta = 800$.

In [9]:
θ = 800
alpha = 1 / θ

# Fit the GLM model
model = smf.glm(
    formula=formula,
    data=df,
    family=sm.families.NegativeBinomial(alpha=alpha),
    offset=np.log(df["n_birth"])
)
results = model.fit(maxiter=1000)

print(results.summary())

                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:                  n_abx   No. Observations:                   38
Model:                            GLM   Df Residuals:                       33
Model Family:        NegativeBinomial   Df Model:                            4
Link Function:                    Log   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -278.04
Date:                Sun, 12 Jul 2026   Deviance:                       28.547
Time:                        12:48:01   Pearson chi2:                     28.5
No. Iterations:                     6   Pseudo R-squ. (CS):              1.000
Covariance Type:            nonrobust
==========================================================================================================
                                             coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------
Intercept                                 74.9725     16.193      4.630      0.000      43.235     106.710
timepoint                                 -0.0377      0.008     -4.664      0.000      -0.054      -0.022
sex                                        0.2602      0.012     21.859      0.000       0.237       0.283
heaviside(timepoint, 2005.0)              93.1945     16.563      5.627      0.000      60.731     125.658
heaviside(timepoint, 2005.0):timepoint    -0.0465      0.008     -5.619      0.000      -0.063      -0.030
==========================================================================================================

Now that the model has been trained, we can obtain the $\beta$ parameters:

In [10]:
β_0 = results.params["Intercept"]
β_t = results.params["timepoint"]
β_s = results.params["sex"]
β_h = results.params["heaviside(timepoint, 2005.0)"]
β_th = results.params["heaviside(timepoint, 2005.0):timepoint"]

## Example: Sex = Male, Year = 2008

In [ ]:
sex = 2
timepoint = 2008
η = β_0 + β_s * sex + β_t * timepoint + β_h * heaviside(timepoint, 2005) + β_th * heaviside(timepoint, 2005) * timepoint

Now, $\eta$ is the number of antibiotics prescribed per number of infants; what we want to know, is
given an age, birth year, and sex, how many antibiotics were prescribed to that person during
infancy? To do so, we need to use the `Negative Binomial` distribution.
First, we compute $\mu$, using the `link function`.

In [12]:
µ = np.exp(η)

Next, we make sure that $\mu > 0.05$:

In [13]:
µ = max(µ, 0.05)
print(f"µ = {µ:.6f}")

µ = 0.676129

The standard parametrization of the Negative Binomial function uses $p$ and $r$, not $\mu$.
So, we need to convert $\mu$ to $p$:

In [14]:
p = θ / (θ + µ)
r = θ
print(f"p = {p:.6f}, r = {r:.4f}")

p = 0.999156, r = 800.0000

The `Negative Binomial` distribution gives us the probability of an infant being prescribed $k$
courses of antibiotics during infancy:

$$
\begin{aligned}
P(Y = k; r, p) := \binom{k+r-1}{k}(1-p)^k p^r
\end{aligned}
$$

In [ ]:
n_abx = np.random.negative_binomial(r, p)
sex = "female" if sex == 1 else "male"
print(f"Number of courses of antibiotics prescribed during infancy to a {sex} person born in {timepoint}: {n_abx}")

The number of antibiotics obtained is just a sampling from the distribution; if we repeated the
selection multiple times, we could get different values. To visualize this, we can look at the
distribution:

In [ ]:
n_abx = np.random.negative_binomial(r, p, size=100000)
fig = px.histogram(
    n_abx,
    nbins=10,
    title=f"Distribution of Antibiotic Courses Prescribed in Infancy<br>Sex = {sex}, Birth Year = {timepoint}",
    color_discrete_sequence=["#09bfc4"],
    width=600
)
fig.update_xaxes(title_text="Number of Courses of Antibiotics", nticks=10)
fig.update_yaxes(title_text="Count")
fig.update_layout(
    legend_title_text="",
    title_x=0.5,
    title_y=0.95,
    margin=dict(t=50), # Adjust top margin for title
    showlegend=False
)
fig.show(config=config)

## Example: Visualize Multiple Years / Sexes

The example above was just the distribution for a single year and sex; we can visualize
multiple years / sexes together:

In [17]:
def compute_abx_distribution_parameters(
    sex: int, timepoint: float, β_0: float, β_s: float, β_t: float, β_h: float, β_th: float, θ: float
):
    η = (
        β_0 + β_s * sex + β_t * timepoint +
        β_h * heaviside(timepoint, 2005) +
        β_th * heaviside(timepoint, 2005) * timepoint
    )
    µ = np.exp(η)
    µ = max(µ, 0.05)  # Ensure µ is greater than 0.05
    p = θ / (θ + µ)
    return p

Let's create a dataframe with even years from `2000` to `2018`:

In [19]:
sexes = [1, 2]
years = list(date_range(dt.datetime(2000, 1, 1), dt.datetime(2018, 1, 1), step=TimeDelta(years=2)))
df_pred = pd.DataFrame(
    data=list(itertools.product(sexes, years)),
    columns=["sex", "timepoint"]
)
df_pred.head()

   sex  timepoint
0    1 2000-01-01
1    1 2002-01-01
2    1 2004-01-01
3    1 2006-01-01
4    1 2008-01-01

Next, let's find $p$ and $r$ for each year / sex combination:

In [20]:
df_pred["p"] = df_pred.apply(
    lambda x: compute_abx_distribution_parameters(
        x["sex"], convert_timepoint_to_numeric(x["timepoint"]), β_0, β_s, β_t, β_h, β_th, θ),
    axis=1
)
df_pred["r"] = r
df_pred.head()

   sex  timepoint         p    r
0    1 2000-01-01  0.998991  800
1    1 2002-01-01  0.999064  800
2    1 2004-01-01  0.999132  800
3    1 2006-01-01  0.999230  800
4    1 2008-01-01  0.999349  800

We now create a second dataframe, which we will use to sample the `Negative Binomial`
distribution.

In [22]:
df_dist = pd.DataFrame(
    data=list(itertools.product(sexes, years, np.zeros(1000))),
    columns=["sex", "timepoint", "nabx"]
)
df_dist = pd.merge(df_dist, df_pred, on=["timepoint", "sex"])
df_dist.head()

   sex  timepoint  nabx         p    r
0    1 2000-01-01   0.0  0.998991  800
1    1 2000-01-01   0.0  0.998991  800
2    1 2000-01-01   0.0  0.998991  800
3    1 2000-01-01   0.0  0.998991  800
4    1 2000-01-01   0.0  0.998991  800

In [23]:
grouped_df = df_dist.groupby(["sex", "timepoint"])
df_dist["nabx"] = grouped_df.apply(
    lambda x: np.random.negative_binomial(x["r"], x["p"], size=len(x)), include_groups=False
).explode().astype(int).values
df_dist.head()

   sex  timepoint  nabx         p    r
0    1 2000-01-01     2  0.998991  800
1    1 2000-01-01     1  0.998991  800
2    1 2000-01-01     0  0.998991  800
3    1 2000-01-01     1  0.998991  800
4    1 2000-01-01     0  0.998991  800

Now we can visualize our results:

In [25]:
color_map={
    2: "#09bfc4",
    1: "#f39c12",
}

fig = px.histogram(
    df_dist,
    x="nabx",
    facet_col="timepoint",
    facet_col_wrap=3,
    color="sex",
    nbins=10,
    title=f"Distribution of Antibiotic Courses Prescribed in Infancy",
    height=1000,
    width=850,
    facet_row_spacing=0.1,
    color_discrete_map=color_map,
    barmode="group"
)
fig.for_each_trace(lambda t: t.update(name="female" if t.name == "1" else "male"))
fig.for_each_annotation(lambda a: a.update(text=a.text.replace("timepoint=", "Timepoint: ")))
fig.update_xaxes(
    title_text="Number of Courses of Antibiotics",
    nticks=10,
    row=1,
    title=dict(font=dict(size=12))
)
fig.update_xaxes(showticklabels=True, nticks=10)
fig.update_yaxes(title_text="Count", col=1)
fig.update_layout(
    legend_title_text="",
    title_x=0.5,
    title_y=0.95,
    margin=dict(t=150), # Adjust top margin for title
    showlegend=True
)
fig.show(config=config)